import bcrypt from "bcryptjs";

// Standard encrypted password for seed accounts ("student123")
const defaultHashedPassword = bcrypt.hashSync("student123", 10);

export const seedUsers = [
  {
    id: "user-priya",
    name: "Priya Sharma",
    email: "priya@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "North Campus",
    hostel: "Kalpana Chawla Hostel, Room 204",
    phone: "+91 98765 43210",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-10T08:00:00.000Z",
  },
  {
    id: "user-arjun",
    name: "Arjun Verma",
    email: "arjun@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Hostel Block B",
    hostel: "Ramanujan Block, Room 312",
    phone: "+91 98765 43211",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-12T09:30:00.000Z",
  },
  {
    id: "user-neha",
    name: "Neha Patel",
    email: "neha@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Girls Hostel 2",
    hostel: "Block C, Room 108",
    phone: "+91 98765 43212",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-14T11:15:00.000Z",
  },
  {
    id: "user-karan",
    name: "Karan Singhal",
    email: "karan@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Library Gate",
    hostel: "Aryabhatta Block, Room 415",
    phone: "+91 98765 43213",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-15T14:20:00.000Z",
  },
  {
    id: "user-rohan",
    name: "Rohan Gupta",
    email: "rohan@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "South Campus",
    hostel: "Block D, Room 114",
    phone: "+91 98765 43214",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-16T10:00:00.000Z",
  },
  {
    id: "user-vikram",
    name: "Vikram Malhotra",
    email: "vikram@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Sports Complex",
    hostel: "Block A, Room 220",
    phone: "+91 98765 43215",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-18T10:00:00.000Z",
  },
];

export const seedListings = [
  // -------------------------------------------------------------
  // 1. BOOKS (3 Items)
  // -------------------------------------------------------------
  {
    id: 1,
    title: "Higher Engineering Mathematics by B.S. Grewal (44th Ed)",
    price: "₹450",
    numericPrice: 450,
    tag: "Like new",
    condition: "Like new",
    place: "North Campus",
    time: "20 min ago",
    seller: "Priya",
    sellerId: "user-priya",
    category: "Books",
    description: "Standard reference textbook for Engineering Mathematics (Sem 1 to 4). Crisp pages with zero pen marks or tears. Complete with all solved exercise sets and formula charts.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 14,
    viewsCount: 142,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    title: "Introduction to Algorithms (CLRS 3rd Edition)",
    price: "₹850",
    numericPrice: 850,
    tag: "Good",
    condition: "Good",
    place: "Library Gate",
    time: "1 hr ago",
    seller: "Karan",
    sellerId: "user-karan",
    category: "Books",
    description: "Comprehensive algorithms bible by Cormen, Leiserson, Rivest, and Stein. Covers greedy algorithms, dynamic programming, graph algorithms, and NP-completeness. Hardbound edition.",
    image: "https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 18,
    viewsCount: 165,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    title: "Concepts of Physics Vol 1 & 2 by H.C. Verma",
    price: "₹500",
    numericPrice: 500,
    tag: "Like new",
    condition: "Like new",
    place: "South Campus",
    time: "2 hrs ago",
    seller: "Rohan",
    sellerId: "user-rohan",
    category: "Books",
    description: "Both Volume 1 and Volume 2 bundled together. Lucid explanations of mechanics, thermodynamics, electromagnetism, and optics with numerical exercises.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 9,
    viewsCount: 88,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 2. ELECTRONICS (3 Items)
  // -------------------------------------------------------------
  {
    id: 4,
    title: "Sony WH-1000XM4 Noise Cancelling Wireless Headphones",
    price: "₹8,500",
    numericPrice: 8500,
    tag: "Like new",
    condition: "Like new",
    place: "North Campus",
    time: "15 min ago",
    seller: "Priya",
    sellerId: "user-priya",
    category: "Electronics",
    description: "Industry-leading active noise cancelling with 30-hour battery life. Original hardshell case, charging cable, and auxiliary cord included. Perfect for focused library study.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 28,
    viewsCount: 240,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    title: "Casio FX-991EX ClassWiz Scientific Calculator",
    price: "₹800",
    numericPrice: 800,
    tag: "Processing",
    condition: "Like new",
    place: "Hostel Block B",
    time: "35 min ago",
    seller: "Arjun",
    sellerId: "user-arjun",
    category: "Electronics",
    description: "552 functions with natural textbook display and matrix/vector modes. College exam approved. Negotiated buyer offer accepted — currently processing transaction.",
    image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=900&q=85",
    status: "processing",
    savesCount: 22,
    viewsCount: 210,
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    title: "Logitech MX Master 3 Wireless Ergonomic Mouse",
    price: "₹4,200",
    numericPrice: 4200,
    tag: "Like new",
    condition: "Like new",
    place: "Academic Block",
    time: "3 hrs ago",
    seller: "Karan",
    sellerId: "user-karan",
    category: "Electronics",
    description: "Ultrafast MagSpeed electromagnetic scroll wheel with 4000 DPI Darkfield tracking on any surface including glass. Connects up to 3 laptops via Bluetooth or USB.",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 16,
    viewsCount: 154,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 3. HOSTEL ITEMS (3 Items)
  // -------------------------------------------------------------
  {
    id: 7,
    title: "Prestige 1.5L Stainless Steel Electric Kettle",
    price: "₹650",
    numericPrice: 650,
    tag: "Like new",
    condition: "Like new",
    place: "Hostel Block B",
    time: "45 min ago",
    seller: "Arjun",
    sellerId: "user-arjun",
    category: "Hostel Items",
    description: "Stainless steel rapid-boil kettle with 360-degree swivel base and automatic dry-boil safety protection. Absolute essential for midnight tea, coffee, and noodles.",
    image: "https://images.unsplash.com/photo-1594213114663-ddf3f2a02126?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 19,
    viewsCount: 160,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 8,
    title: "Minimal LED Study Desk Lamp with Touch Dimming",
    price: "₹750",
    numericPrice: 750,
    tag: "Like new",
    condition: "Like new",
    place: "Girls Hostel 2",
    time: "1 hr ago",
    seller: "Neha",
    sellerId: "user-neha",
    category: "Hostel Items",
    description: "Eye-care non-flicker LED lamp with 3 color temperatures (warm, neutral, cool) and built-in 2000mAh rechargeable battery for hostel night power cuts.",
    image: "https://images.unsplash.com/photo-1519219788971-8d9797e0928e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 12,
    viewsCount: 110,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    title: "Foldable Wooden Bed Study Table with Cup Holder",
    price: "₹420",
    numericPrice: 420,
    tag: "Good",
    condition: "Good",
    place: "Hostel Block A",
    time: "4 hrs ago",
    seller: "Rohan",
    sellerId: "user-rohan",
    category: "Hostel Items",
    description: "Portable laptop bed desk with dedicated tablet slot and cup holder. Sturdy curved legs with anti-slip pads. Folds flat in 2 seconds for easy storage under bed.",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 15,
    viewsCount: 125,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 4. SPORTS (3 Items)
  // -------------------------------------------------------------
  {
    id: 10,
    title: "Yonex Muscle Power 29 Badminton Racket with Cover",
    price: "₹1,400",
    numericPrice: 1400,
    tag: "Like new",
    condition: "Like new",
    place: "Sports Complex",
    time: "30 min ago",
    seller: "Vikram",
    sellerId: "user-vikram",
    category: "Sports",
    description: "Isometric frame with titanium mesh construction. Strung at 24 lbs with Yonex BG-65 gut. Perfectly balanced for fast smashes and court control. Padded cover included.",
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 20,
    viewsCount: 180,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 11,
    title: "Nivia Storm Football (Size 5, FIFA Spec)",
    price: "₹480",
    numericPrice: 480,
    tag: "Good",
    condition: "Good",
    place: "Central Cafeteria",
    time: "2 hrs ago",
    seller: "Karan",
    sellerId: "user-karan",
    category: "Sports",
    description: "32-panel rubber molded ball built for rough campus ground surfaces. Excellent air retention with reinforced butyl bladder. Clean and well maintained.",
    image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 8,
    viewsCount: 92,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 12,
    title: "SG Kashmir Willow Cricket Bat with Extra Grip",
    price: "₹1,850",
    numericPrice: 1850,
    tag: "Good",
    condition: "Good",
    place: "Sports Complex",
    time: "5 hrs ago",
    seller: "Vikram",
    sellerId: "user-vikram",
    category: "Sports",
    description: "Grade 1 Kashmir willow short handle cricket bat. Thick edges with curved profile for powerful strokes. Pre-knocked with fiber protective face tape and toe guard.",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 14,
    viewsCount: 130,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 5. CLOTHING (3 Items)
  // -------------------------------------------------------------
  {
    id: 13,
    title: "Official University Tech Varsity Hoodie (Navy, Size L)",
    price: "₹550",
    numericPrice: 550,
    tag: "Like new",
    condition: "Like new",
    place: "Girls Hostel 1",
    time: "50 min ago",
    seller: "Neha",
    sellerId: "user-neha",
    category: "Clothing",
    description: "Heavyweight 380 GSM fleece university hoodie in classic navy blue. Double-lined hood, kangaroo pouch pocket, washed and sanitized.",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 11,
    viewsCount: 104,
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
  },
  {
    id: 14,
    title: "Levi's Classic Denim Trucker Jacket (Unisex M)",
    price: "₹1,600",
    numericPrice: 1600,
    tag: "Good",
    condition: "Good",
    place: "North Campus",
    time: "3 hrs ago",
    seller: "Priya",
    sellerId: "user-priya",
    category: "Clothing",
    description: "Original 100% cotton denim jacket in medium stonewash. Welt side pockets and button flap chest pockets. Durable, iconic campus outerwear.",
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 17,
    viewsCount: 140,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 15,
    title: "Formal Navy Blazer for Campus Placements (Size 38)",
    price: "₹2,100",
    numericPrice: 2100,
    tag: "Brand new",
    condition: "Brand new",
    place: "South Campus",
    time: "6 hrs ago",
    seller: "Rohan",
    sellerId: "user-rohan",
    category: "Clothing",
    description: "Worn just once for college placement day. Single-breasted two-button design with notch lapel. Professionally dry-cleaned, stored in breathable garment cover.",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 21,
    viewsCount: 175,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 6. ACCESSORIES (3 Items)
  // -------------------------------------------------------------
  {
    id: 16,
    title: "Wildcraft 32L Weatherproof Laptop Backpack",
    price: "₹1,200",
    numericPrice: 1200,
    tag: "Good",
    condition: "Good",
    place: "Hostel Block B",
    time: "1 hr ago",
    seller: "Arjun",
    sellerId: "user-arjun",
    category: "Accessories",
    description: "Ergonomic multi-compartment bag with padded 15.6-inch laptop compartment, side mesh bottle holders, and integrated high-visibility rain cover.",
    image: "https://images.unsplash.com/photo-1622560481156-01fc7e1693e6?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 13,
    viewsCount: 118,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 17,
    title: "Fastrack Reflex Smartwatch with Dual Strap Set",
    price: "₹1,450",
    numericPrice: 1450,
    tag: "Like new",
    condition: "Like new",
    place: "Library Gate",
    time: "2 hrs ago",
    seller: "Karan",
    sellerId: "user-karan",
    category: "Accessories",
    description: "1.83-inch HD display with Bluetooth phone calling, heart rate tracking, sleep monitor, and 7-day battery life. Includes magnetic charging dock and 2 quick-swap straps.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 19,
    viewsCount: 162,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 18,
    title: "Ray-Ban Aviator Classic Sunglasses with Case",
    price: "₹2,800",
    numericPrice: 2800,
    tag: "Like new",
    condition: "Like new",
    place: "Academic Block",
    time: "4 hrs ago",
    seller: "Vikram",
    sellerId: "user-vikram",
    category: "Accessories",
    description: "Golden metal frame with crystal green G-15 100% UV protection lenses. Authentic with original leather case and cleaning cloth.",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 15,
    viewsCount: 135,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 7. VEHICLES (3 Items)
  // -------------------------------------------------------------
  {
    id: 19,
    title: "Hero Sprint 21-Speed Gear Bicycle with Wire Lock",
    price: "₹3,200",
    numericPrice: 3200,
    tag: "Good",
    condition: "Good",
    place: "Hostel Block B",
    time: "1 hr ago",
    seller: "Arjun",
    sellerId: "user-arjun",
    category: "Vehicles",
    description: "Lightweight aluminum frame bicycle with Shimano thumb shifters and dual disc brakes. Great for commuting between hostel and departments. Free heavy-duty spiral lock included.",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 26,
    viewsCount: 230,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 20,
    title: "Honda Activa 6G Scooter (2023, 8200 km, Single Owner)",
    price: "₹42,000",
    numericPrice: 42000,
    tag: "Good",
    condition: "Good",
    place: "South Campus",
    time: "3 hrs ago",
    seller: "Rohan",
    sellerId: "user-rohan",
    category: "Vehicles",
    description: "High mileage 110cc scooter in superb condition. Serviced only at authorized Honda center with valid insurance till March 2027. Includes Studds helmet and USB mobile charger.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 34,
    viewsCount: 310,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 21,
    title: "Btwin Riverside Hybrid Commuter Bicycle with Basket",
    price: "₹4,800",
    numericPrice: 4800,
    tag: "Like new",
    condition: "Like new",
    place: "North Campus",
    time: "5 hrs ago",
    seller: "Priya",
    sellerId: "user-priya",
    category: "Vehicles",
    description: "Comfortable ergonomic saddle with front suspension fork and 28-inch hybrid road tires. Quick-release wheels and detachable front basket for books/bags.",
    image: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 22,
    viewsCount: 190,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },

  // -------------------------------------------------------------
  // 8. OTHER (3 Items)
  // -------------------------------------------------------------
  {
    id: 22,
    title: "Yamaha F310 Acoustic Guitar with Padded Gig Bag",
    price: "₹4,900",
    numericPrice: 4900,
    tag: "Good",
    condition: "Good",
    place: "Central Cafeteria",
    time: "1 hr ago",
    seller: "Vikram",
    sellerId: "user-vikram",
    category: "Other",
    description: "Spruce top acoustic guitar with warm, resonant projection. Rosewood fingerboard with low string action for effortless chord transitions. Includes tuner, picks, and strap.",
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 18,
    viewsCount: 165,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 23,
    title: "Engineering Drafting Board (A2) with Mini Drafter & Clips",
    price: "₹1,100",
    numericPrice: 1100,
    tag: "Good",
    condition: "Good",
    place: "Academic Block",
    time: "2 hrs ago",
    seller: "Karan",
    sellerId: "user-karan",
    category: "Other",
    description: "Complete Engineering Drawing kit: smooth pine wood A2 board, Omega 360-degree mini-drafter with stainless steel scales, set squares, and water-repellent canvas bag.",
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 10,
    viewsCount: 95,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 24,
    title: "Orthopedic Memory Foam Seat Cushion for Study Chair",
    price: "₹680",
    numericPrice: 680,
    tag: "Like new",
    condition: "Like new",
    place: "Library Gate",
    time: "4 hrs ago",
    seller: "Neha",
    sellerId: "user-neha",
    category: "Other",
    description: "Ergonomic U-shaped coccyx relief cushion for long study marathons in the hostel or library. High-density responsive memory foam with breathable, machine-washable cover.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 14,
    viewsCount: 120,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export const seedOffers = [
  {
    id: "offer-1",
    listingId: 5,
    listingTitle: "Casio FX-991EX ClassWiz Scientific Calculator",
    originalPrice: 800,
    offerAmount: 650,
    buyerId: "user-priya",
    buyerName: "Priya Sharma",
    sellerId: "user-arjun",
    sellerName: "Arjun Verma",
    status: "accepted",
    message: "Hey Arjun, can pick it up today at Hostel Block B for ₹650 in cash or UPI!",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];

export const seedConversations = [
  {
    id: "conv-1",
    listingId: 5,
    buyerId: "user-priya",
    sellerId: "user-arjun",
    lastMessage: "🤝 Offer of ₹650 ACCEPTED! Transaction is now PROCESSING.",
    lastMessageAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    unreadCountPriya: 0,
    unreadCountArjun: 0,
  },
];

export const seedMessages = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-priya",
    senderName: "Priya Sharma",
    receiverId: "user-arjun",
    receiverName: "Arjun Verma",
    text: "Hey Arjun! Is the Casio calculator still available?",
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-arjun",
    senderName: "Arjun Verma",
    receiverId: "user-priya",
    receiverName: "Priya Sharma",
    text: "Yes, it is! In great condition with slide-on case. What's your offer?",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-3",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-priya",
    senderName: "Priya Sharma",
    receiverId: "user-arjun",
    receiverName: "Arjun Verma",
    text: "Offer made: ₹650 - Hey Arjun, can pick it up today at Hostel Block B for ₹650 in cash or UPI!",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-4",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-arjun",
    senderName: "Arjun Verma",
    receiverId: "user-priya",
    receiverName: "Priya Sharma",
    text: "🤝 Offer of ₹650 ACCEPTED! Transaction is now PROCESSING. Let's meet at the Block B cafeteria at 5 PM.",
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];

export const seedSavedListings = [
  {
    id: "saved-1",
    userId: "user-priya",
    listingId: 4,
    savedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "saved-2",
    userId: "user-priya",
    listingId: 10,
    savedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];

export const seedData = {
  users: seedUsers,
  listings: seedListings,
  offers: seedOffers,
  conversations: seedConversations,
  messages: seedMessages,
  savedListings: seedSavedListings,
};

export default seedData;
