import bcrypt from "bcryptjs";

// Password for all seeded demo users is "student123"
const defaultHashedPassword = bcrypt.hashSync("student123", 10);

export const seedUsers = [
  {
    id: "user-aarav",
    name: "Aarav Sharma",
    email: "aarav@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "North Campus",
    hostel: "Ramanujan Hostel, Room 304",
    phone: "+91 98765 43210",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-10T08:00:00.000Z",
  },
  {
    id: "user-meera",
    name: "Meera Patel",
    email: "meera@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Hostel Block B",
    hostel: "Block B, Room 212",
    phone: "+91 98765 43211",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-12T09:30:00.000Z",
  },
  {
    id: "user-kabir",
    name: "Kabir Sen",
    email: "kabir@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Library Gate",
    hostel: "Aryabhatta Block, Room 108",
    phone: "+91 98765 43212",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-14T11:15:00.000Z",
  },
  {
    id: "user-ananya",
    name: "Ananya Roy",
    email: "ananya@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "Girls Hostel 2",
    hostel: "Kalpana Chawla Block, Room 415",
    phone: "+91 98765 43213",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-15T14:20:00.000Z",
  },
  {
    id: "user-rahul",
    name: "Rahul Sharma",
    email: "rahul@campus.edu",
    passwordHash: defaultHashedPassword,
    university: "Delhi Technological University",
    campusLocation: "South Campus",
    hostel: "Block C, Room 114",
    phone: "+91 98765 43214",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80",
    verified: true,
    createdAt: "2025-01-16T10:00:00.000Z",
  },
];

export const seedListings = [
  {
    id: 1,
    title: "Sony WH-1000XM4 Headphones",
    price: "₹8,500",
    numericPrice: 8500,
    tag: "Like new",
    condition: "Like new",
    place: "North Campus",
    time: "18 min ago",
    seller: "Aarav",
    sellerId: "user-aarav",
    category: "Electronics",
    description: "Industry-leading noise cancelling wireless headphones. Flawless battery life with original AUX cable, charging wire, and hardshell travel case. Used sparingly for quiet library study sessions.",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 14,
    viewsCount: 142,
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    title: "Wildcraft Everyday Backpack",
    price: "₹1,200",
    numericPrice: 1200,
    tag: "Good",
    condition: "Good",
    place: "Hostel Block B",
    time: "45 min ago",
    seller: "Meera",
    sellerId: "user-meera",
    category: "Accessories",
    description: "Durable 32L weather-resistant campus backpack. Features dedicated padded compartment for 15.6 inch laptops, quick-access organiser, and attached tuck-away rain cover.",
    image: "https://images.unsplash.com/photo-1622560481156-01fc7e1693e6?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 6,
    viewsCount: 88,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    title: "Engineering Semester Books",
    price: "₹950",
    numericPrice: 950,
    tag: "Good",
    condition: "Good",
    place: "Library Gate",
    time: "1 hr ago",
    seller: "Kabir",
    sellerId: "user-kabir",
    category: "Books",
    description: "Comprehensive bundle of 4 core engineering textbooks: Data Structures & Algorithms, Digital Circuit Design, Engineering Math, and Discrete Structures. Crisp pages with helpful highlighted key formulas.",
    image: "https://images.unsplash.com/photo-1516889454133-d3cd87326a6b?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 9,
    viewsCount: 120,
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    title: "Minimal Study Desk Lamp",
    price: "₹750",
    numericPrice: 750,
    tag: "Like new",
    condition: "Like new",
    place: "Girls Hostel 2",
    time: "2 hrs ago",
    seller: "Ananya",
    sellerId: "user-ananya",
    category: "Hostel Items",
    description: "Eye-care LED desk lamp with 3 color temperatures (warm, natural, cool white) and stepless touch dimming. Built-in rechargeable 2000mAh battery for night power cuts.",
    image: "https://images.unsplash.com/photo-1519219788971-8d9797e0928e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 11,
    viewsCount: 95,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    title: "Casio FX-991EX Scientific Calculator",
    price: "₹800",
    numericPrice: 800,
    tag: "Like new",
    condition: "Like new",
    place: "North Campus",
    time: "3 hrs ago",
    seller: "Aarav",
    sellerId: "user-aarav",
    category: "Electronics",
    description: "Official ClassWiz high-resolution natural textbook display with 552 functions including matrix, vector, and equation calculations. Exam board approved, protective slide-on hard case included.",
    image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 22,
    viewsCount: 210,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    title: "Hero Sprint 21-Speed Campus Bicycle",
    price: "₹3,200",
    numericPrice: 3200,
    tag: "Good",
    condition: "Good",
    place: "Hostel Block B",
    time: "4 hrs ago",
    seller: "Meera",
    sellerId: "user-meera",
    category: "Vehicles",
    description: "Sturdy aluminum frame bicycle with Shimano 21-speed thumb shifters and dual disc brakes. Perfect for riding between hostel and lecture halls. Free heavy-duty spiral wire lock included.",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 17,
    viewsCount: 184,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 9,
    title: "Honda Activa 6G (2023) Campus Scooter",
    price: "₹42,000",
    numericPrice: 42000,
    tag: "Good",
    condition: "Good",
    place: "South Campus",
    time: "3 hrs ago",
    seller: "Rahul",
    sellerId: "user-rahul",
    category: "Vehicles",
    description: "Single-owner Honda Activa 6G with only 8,200 km on the odometer. Regular serviced at authorized center, fresh insurance till March 2027. Alloy wheels, mobile charger, and helmet included.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 23,
    viewsCount: 210,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 7,
    title: "Prestige 1.5L Electric Kettle for Hostel",
    price: "₹650",
    numericPrice: 650,
    tag: "Like new",
    condition: "Like new",
    place: "Library Gate",
    time: "5 hrs ago",
    seller: "Kabir",
    sellerId: "user-kabir",
    category: "Hostel Items",
    description: "Stainless steel rapid-boil electric kettle with concealed heating element, 360-degree swivel base, and automatic dry boil protection. Must-have for late night ramen and coffee.",
    image: "https://images.unsplash.com/photo-1594213114663-ddf3f2a02126?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 8,
    viewsCount: 76,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 8,
    title: "Official Campus Tech Hoodie (Unisex L)",
    price: "₹550",
    numericPrice: 550,
    tag: "Like new",
    condition: "Like new",
    place: "Girls Hostel 2",
    time: "6 hrs ago",
    seller: "Ananya",
    sellerId: "user-ananya",
    category: "Clothing",
    description: "Ultra-comfortable 380 GSM fleece university tech hoodie in dark navy. Roomy kangaroo pocket, lined hood, washed and sanitized.",
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=85",
    status: "available",
    savesCount: 5,
    viewsCount: 62,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
];

export const seedOffers = [
  {
    id: "offer-1",
    listingId: 5,
    listingTitle: "Casio FX-991EX Scientific Calculator",
    originalPrice: 800,
    offerAmount: 650,
    buyerId: "user-rahul",
    buyerName: "Rahul Sharma",
    sellerId: "user-aarav",
    sellerName: "Aarav Sharma",
    status: "pending",
    message: "Hey Aarav, can pick it up today at North Campus for ₹650 in cash or UPI!",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const seedConversations = [
  {
    id: "conv-1",
    listingId: 5,
    buyerId: "user-rahul",
    sellerId: "user-aarav",
    lastMessage: "Rahul offered ₹650",
    lastMessageAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    unreadCountAarav: 1,
    unreadCountRahul: 0,
  },
];

export const seedMessages = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-rahul",
    senderName: "Rahul Sharma",
    receiverId: "user-aarav",
    receiverName: "Aarav",
    text: "Hey! Is the calculator still available?",
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    listingId: 5,
    senderId: "user-aarav",
    senderName: "Aarav",
    receiverId: "user-rahul",
    receiverName: "Rahul Sharma",
    text: "Yes! It's in great condition. Want to make an offer?",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
];

export const seedSavedListings = [
  {
    id: "saved-1",
    userId: "user-rahul",
    listingId: 5,
    savedAt: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
  },
  {
    id: "saved-2",
    userId: "user-rahul",
    listingId: 1,
    savedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
];
